# Generated by Django 3.2.7 on 2021-09-29 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AddField(
            model_name='contact',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='generalmodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
