# Generated by Django 3.2.7 on 2021-09-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppy', '0002_auto_20210929_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Person'},
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(max_length=15, null=True, verbose_name='Sex'),
        ),
        migrations.AddField(
            model_name='contact',
            name='insurance_number',
            field=models.PositiveIntegerField(null=True, verbose_name='SNILS'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tax_id',
            field=models.PositiveIntegerField(null=True, verbose_name='INN'),
        ),
    ]
