# Generated by Django 3.2 on 2021-10-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puppy', '0005_auto_20211015_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='person_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='puppy.person'),
            preserve_default=False,
        ),
    ]
