# Generated by Django 3.2 on 2021-10-15 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puppy', '0006_address_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('generalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puppy.generalmodel')),
            ],
            bases=('puppy.generalmodel',),
        ),
        migrations.AlterField(
            model_name='address',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_address', to='puppy.person'),
        ),
    ]
