# Generated by Django 3.2 on 2021-10-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puppy', '0008_auto_20211015_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('generalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puppy.generalmodel')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
            bases=('puppy.generalmodel',),
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('generalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puppy.generalmodel')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('job_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность')),
                ('role', models.CharField(blank=True, max_length=200, null=True, verbose_name='Роль')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career', to='puppy.company')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career', to='puppy.person')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career', to='puppy.project')),
            ],
            options={
                'verbose_name': 'Карьерный путь',
                'verbose_name_plural': 'Карьерный путь',
            },
            bases=('puppy.generalmodel',),
        ),
    ]
